yolo_model:

  config_file:
    name: tiny-yolo-voc-person.cfg
  weight_file:
    name: tiny-yolo-voc-person-red_final.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
